### PR TITLE
Moved trainer initialization to outside of fit method

### PR DESCRIPTION
**Pull request by sebastianruder**
Hi @bplank,

I've moved the trainer initialization to outside of the `fit` method (see the PR that references this one).

### CODE REVIEW

**Comment by bplank** [comment]
the `set_clip_threshold` was still over, I've moved the initialization to the constructor. 

If you agree we can merge this.

**Comment by sebastianruder** [comment]
Ok, cool. Maybe just don't set the default of the learning rate to `0` but instead to `0.001` so we don't run into a weird bug in case we forget to set it by accident.

**Comment by bplank** [comment]
Ok great, let me set it to the default of Adam (0.001) and remove the
ugly if-else.

**Comment by sebastianruder** [comment]
Ok, cool! Looks good! :)

**Pull request merged**
